--- arch/arm/lib/Makefile
+++ arch/arm/lib/Makefile
@@ -6,8 +6,8 @@
 
 lib-y		:= backtrace.o changebit.o csumipv6.o csumpartial.o   \
 		   csumpartialcopy.o csumpartialcopyuser.o clearbit.o \
-		   delay.o findbit.o memchr.o			      \
-		   memset.o memzero.o setbit.o                        \
+		   delay.o findbit.o memchr.o memcpy.o		      \
+		   memmove.o memset.o memzero.o setbit.o              \
 		   strncpy_from_user.o strnlen_user.o                 \
 		   strchr.o strrchr.o                                 \
 		   testchangebit.o testclearbit.o testsetbit.o        \
@@ -16,13 +16,10 @@ lib-y		:= backtrace.o changebit.o csumipv6.o csumpartial.o   \
 		   io-readsb.o io-writesb.o io-readsl.o io-writesl.o  \
 		   call_with_stack.o
 
-mmu-y	:= clear_user.o getuser.o putuser.o
+mmu-y	:= clear_user.o copy_page.o getuser.o putuser.o
 
 # the code in uaccess.S is not preemption safe and
 # probably faster on ARMv3 only
-ifneq ($(CONFIG_HAS_MACH_MEMUTILS),y)
-  mmu-y += copy_page.o
-  lib-y += memmove.o memcpy.o
 ifeq ($(CONFIG_PREEMPT),y)
   mmu-y	+= copy_from_user.o copy_to_user.o
 else
@@ -32,7 +29,6 @@ else
   mmu-y	+= uaccess.o
 endif
 endif
-endif
 
 # using lib_ here won't override already available weak symbols
 obj-$(CONFIG_UACCESS_WITH_MEMCPY) += uaccess_with_memcpy.o
